'use client';

import React, { useEffect, useState } from 'react';
import { Brain, Search, Trash2, Plus, Sparkles, AlertCircle, RefreshCw } from 'lucide-react';
import GlowingCard from '@/components/glowing-card';

interface Memory {
  id: string;
  content: string;
  category: string;
  sentiment: string | null;
  createdAt: string;
  similarity?: number;
}

export default function MemoriesPage() {
  const [memories, setMemories] = useState<Memory[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('ALL');
  
  // Create state
  const [newContent, setNewContent] = useState('');
  const [newCategory, setNewCategory] = useState('PERSONAL');
  const [createLoading, setCreateLoading] = useState(false);

  // Search state
  const [isSearching, setIsSearching] = useState(false);

  const fetchMemories = async (cat = selectedCategory) => {
    setLoading(true);
    try {
      const url = cat === 'ALL' ? '/api/memories' : `/api/memories?category=${cat}`;
      const res = await fetch(url);
      if (!res.ok) throw new Error('Failed to load memories');
      const data = await res.json();
      setMemories(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchMemories();
  }, [selectedCategory]);

  const handleCreate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newContent.trim()) return;

    setCreateLoading(true);
    try {
      const res = await fetch('/api/memories', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          content: newContent,
          category: newCategory,
        }),
      });

      if (!res.ok) throw new Error('Failed to create memory');
      
      setNewContent('');
      fetchMemories();
    } catch (err) {
      console.error(err);
    } finally {
      setCreateLoading(false);
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm('Are you sure you want to delete this memory node?')) return;

    try {
      const res = await fetch(`/api/memories?id=${id}`, {
        method: 'DELETE',
      });
      if (!res.ok) throw new Error('Failed to delete memory');
      
      setMemories((prev) => prev.filter((m) => m.id !== id));
    } catch (err) {
      console.error(err);
    }
  };

  const handleSearch = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!searchQuery.trim()) {
      fetchMemories();
      return;
    }

    setIsSearching(true);
    setLoading(true);
    try {
      const res = await fetch('/api/memories', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'search',
          query: searchQuery,
          category: selectedCategory === 'ALL' ? undefined : selectedCategory,
        }),
      });

      if (!res.ok) throw new Error('Search failed');
      const data = await res.json();
      setMemories(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
      setIsSearching(false);
    }
  };

  const getCategoryColor = (cat: string) => {
    switch (cat.toUpperCase()) {
      case 'PERSONAL':
        return 'text-indigo-400 bg-indigo-500/5 border-indigo-500/10';
      case 'CAREER':
        return 'text-emerald-400 bg-emerald-500/5 border-emerald-500/10';
      case 'LEARNING':
        return 'text-purple-400 bg-purple-500/5 border-purple-500/10';
      case 'PROJECT':
        return 'text-amber-400 bg-amber-500/5 border-amber-500/10';
      default:
        return 'text-slate-400 bg-slate-500/5 border-slate-500/10';
    }
  };

  return (
    <div className="flex flex-col gap-8">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 border-b border-[rgba(255,255,255,0.04)] pb-6">
        <div className="flex flex-col gap-1">
          <h1 className="text-3xl font-extrabold text-white tracking-tight flex items-center gap-2.5">
            Long-term Memory <span className="text-indigo-400 glow-text font-light">Index</span>
          </h1>
          <p className="text-sm text-slate-400 font-medium">
            Search, filter, or append memory nodes generated by your interactions.
          </p>
        </div>
      </div>

      {/* Grid: Search and Filter + Create Card */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Left/Middle: Memory List (span 2) */}
        <div className="lg:col-span-2 flex flex-col gap-6">
          
          {/* Query Bar */}
          <div className="glass rounded-2xl p-4 border border-[rgba(255,255,255,0.05)]">
            <form onSubmit={handleSearch} className="flex gap-2">
              <div className="relative flex-1">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" size={16} />
                <input
                  type="text"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  placeholder="Ask your second brain (e.g. 'what coding language do I use?')"
                  className="w-full pl-10 pr-4 py-2.5 bg-[rgba(255,255,255,0.02)] border border-[rgba(255,255,255,0.06)] rounded-xl text-sm text-white placeholder-slate-600 focus:outline-none focus:border-indigo-500 transition-colors"
                />
              </div>
              <button
                type="submit"
                className="flex items-center gap-1.5 px-4 py-2.5 bg-gradient-to-r from-indigo-500 to-purple-600 text-white font-semibold rounded-xl text-xs cursor-pointer shadow hover:brightness-110 active:scale-95 transition-all"
              >
                <Sparkles size={12} />
                Query
              </button>
            </form>

            {/* Filter Tabs */}
            <div className="flex items-center gap-2 mt-4 overflow-x-auto pb-1">
              {['ALL', 'PERSONAL', 'CAREER', 'LEARNING', 'PROJECT'].map((cat) => (
                <button
                  key={cat}
                  onClick={() => setSelectedCategory(cat)}
                  className={`text-[10px] font-mono font-bold px-3 py-1.5 rounded-lg border cursor-pointer transition-all uppercase whitespace-nowrap ${
                    selectedCategory === cat
                      ? 'bg-indigo-500/10 border-indigo-500/30 text-indigo-300 shadow'
                      : 'border-transparent text-slate-500 hover:text-slate-300 hover:bg-white/2'
                  }`}
                >
                  {cat}
                </button>
              ))}
            </div>
          </div>

          {/* Results Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {loading ? (
              <div className="col-span-full flex justify-center py-12">
                <RefreshCw size={24} className="animate-spin text-indigo-500" />
              </div>
            ) : memories.length === 0 ? (
              <div className="col-span-full glass rounded-2xl py-12 text-center border border-dashed border-slate-800">
                <AlertCircle className="text-slate-600 mx-auto mb-2" size={24} />
                <p className="text-xs text-slate-500 font-mono">No matching memory nodes index.</p>
              </div>
            ) : (
              memories.map((mem) => (
                <div
                  key={mem.id}
                  className="glass p-5 rounded-2xl border border-[rgba(255,255,255,0.04)] hover:border-[rgba(99,102,241,0.15)] glow-border transition-all flex flex-col justify-between gap-4 group"
                >
                  <p className="text-xs text-slate-200 leading-relaxed font-semibold italic">
                    &quot;{mem.content}&quot;
                  </p>
                  
                  <div className="flex items-center justify-between border-t border-[rgba(255,255,255,0.03)] pt-3.5">
                    <div className="flex items-center gap-2">
                      <span className={`text-[9px] font-mono font-bold px-2 py-0.5 border rounded-md uppercase ${getCategoryColor(mem.category)}`}>
                        {mem.category}
                      </span>
                      {mem.similarity !== undefined && (
                        <span className="text-[9px] font-mono text-indigo-400 font-bold bg-indigo-500/5 px-2 py-0.5 rounded border border-indigo-500/10">
                          {Math.round(mem.similarity * 100)}% Similarity
                        </span>
                      )}
                    </div>

                    <div className="flex items-center gap-2">
                      <span className="text-[9px] font-mono text-slate-500">
                        {new Date(mem.createdAt).toLocaleDateString()}
                      </span>
                      <button
                        onClick={() => handleDelete(mem.id)}
                        className="text-slate-600 hover:text-red-400 cursor-pointer p-1 rounded-md transition-colors"
                        title="Delete memory node"
                      >
                        <Trash2 size={12} />
                      </button>
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>

        {/* Right Column: Append Memory Card */}
        <GlowingCard title="Append Memory Node" subtitle="Manually index user context guidelines">
          <form onSubmit={handleCreate} className="flex flex-col gap-4 mt-2">
            <div className="flex flex-col gap-1.5">
              <label className="text-[10px] uppercase tracking-wider text-slate-500 font-mono font-bold">
                Context Category
              </label>
              <select
                value={newCategory}
                onChange={(e) => setNewCategory(e.target.value)}
                className="w-full px-3.5 py-2.5 bg-[#0c0c1e] border border-slate-800 rounded-xl text-xs text-white focus:outline-none focus:border-indigo-500"
              >
                <option value="PERSONAL">Personal Preference</option>
                <option value="CAREER">Career/Professional</option>
                <option value="LEARNING">Study/Skill Log</option>
                <option value="PROJECT">Project Milestone</option>
              </select>
            </div>

            <div className="flex flex-col gap-1.5">
              <label className="text-[10px] uppercase tracking-wider text-slate-500 font-mono font-bold">
                Memory Statement
              </label>
              <textarea
                value={newContent}
                onChange={(e) => setNewContent(e.target.value)}
                placeholder="User prefers learning dynamically using hands-on repositories..."
                rows={4}
                required
                className="w-full px-3.5 py-2.5 bg-[rgba(255,255,255,0.02)] border border-[rgba(255,255,255,0.08)] rounded-xl text-xs text-white placeholder-slate-600 focus:outline-none focus:border-indigo-500 transition-colors resize-none"
              />
            </div>

            <button
              type="submit"
              disabled={createLoading}
              className="w-full py-3.5 bg-gradient-to-r from-indigo-500 to-purple-600 text-white font-semibold rounded-xl text-xs cursor-pointer shadow hover:scale-[1.01] hover:brightness-110 transition-all flex items-center justify-center gap-1.5 mt-2"
            >
              {createLoading ? (
                <div className="w-4 h-4 border-2 border-white/20 border-t-white rounded-full animate-spin" />
              ) : (
                <>
                  <Plus size={14} />
                  Record Node
                </>
              )}
            </button>
          </form>
        </GlowingCard>
      </div>
    </div>
  );
}
